# Use an official Python runtime as the base image
FROM python:3.8-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt /app/

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container
COPY . /app/

# Specify environment variables if necessary
ENV FLASK_APP=run.py
ENV FLASK_ENV=production

# Expose the port the app runs on (not needed for Heroku)
# EXPOSE 5000

# Run the app. CMD is required to run on Heroku
# $PORT is set by Heroku
CMD flask run --host 0.0.0.0 --port $PORT
